export const certificatesData = [
  {
    id: 1,
    phaseId: 1,
    phaseName: "Phase 1: Foundations of AI",
    recipientName: "Sani",
    cohortName: "AI From Zero To Hero — Cohort 3",
    issuedDate: "2026-08-15",
    credentialId: "EJZ-AI-C3-P1-0001",
    status: "earned",
    grade: "Distinction",
    score: 92,
    skills: [
      "Python Fundamentals",
      "NumPy & Pandas",
      "Linear Algebra",
      "Data Visualization",
    ],
    verificationUrl: "https://ejaztech.com/verify/EJZ-AI-C3-P1-0001",
  },
  {
    id: 2,
    phaseId: 2,
    phaseName: "Phase 2: Supervised Machine Learning",
    recipientName: "Sani",
    cohortName: "AI From Zero To Hero — Cohort 3",
    issuedDate: null,
    credentialId: null,
    status: "in-progress",
    grade: null,
    score: null,
    skills: [],
    verificationUrl: null,
  },
  {
    id: 3,
    phaseId: 3,
    phaseName: "Phase 3: Unsupervised & Deep Learning",
    recipientName: "Sani",
    cohortName: "AI From Zero To Hero — Cohort 3",
    issuedDate: null,
    credentialId: null,
    status: "locked",
    grade: null,
    score: null,
    skills: [],
    verificationUrl: null,
  },
    {
    id: 4,
    phaseId: 4,
    phaseName: "Phase 4: Unsupervised & Deep Learning",
    recipientName: "Sani",
    cohortName: "AI From Zero To Hero — Cohort 3",
    issuedDate: null,
    credentialId: null,
    status: "locked",
    grade: null,
    score: null,
    skills: [],
    verificationUrl: null,
  },
];