export const notificationsData = [
  {
    id: 1,
    type: "achievement",
    title: "New badge unlocked!",
    message: "You earned the '7-Day Streak' badge. Keep it up!",
    time: "2 min ago",
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    read: false,
    action: { label: "View Badge", href: "/certificates" },
  },
  {
    id: 2,
    type: "course",
    title: "New lesson available",
    message: "Phase 2, Week 3: 'Decision Trees & Random Forests' is now unlocked.",
    time: "1 hour ago",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    read: false,
    action: { label: "Continue Learning", href: "/dashbord" },
  },
  {
    id: 3,
    type: "leaderboard",
    title: "You moved up 2 ranks!",
    message: "You're now rank #4 on the leaderboard. 260 XP to reach the podium.",
    time: "3 hours ago",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    read: false,
    action: { label: "View Leaderboard", href: "/leaderboard" },
  },
  {
    id: 4,
    type: "quiz",
    title: "Quiz reminder",
    message: "'Supervised Learning Basics' quiz closes in 2 days. Don't miss it.",
    time: "5 hours ago",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    read: true,
    action: { label: "Take Quiz", href: "/quizzes" },
  },
  {
    id: 5,
    type: "system",
    title: "Scheduled maintenance",
    message: "The platform will be briefly unavailable on Sunday 2:00–3:00 AM.",
    time: "Yesterday",
    timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000),
    read: true,
    action: null,
  },
  {
    id: 6,
    type: "achievement",
    title: "Cohort milestone reached",
    message: "Your cohort completed 10,000 total XP this week. Amazing work!",
    time: "2 days ago",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    read: true,
    action: null,
  },
  {
    id: 7,
    type: "course",
    title: "New resource added",
    message: "A cheat sheet for 'Supervised Machine Learning' was added to Phase 2.",
    time: "3 days ago",
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    read: true,
    action: { label: "View Resource", href: "/phases" },
  },
  {
    id: 8,
    type: "leaderboard",
    title: "Weekly leaderboard reset",
    message: "A new week has started. Climb the ranks and earn your spot!",
    time: "5 days ago",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    read: true,
    action: { label: "View Leaderboard", href: "/leaderboard" },
  },
];