export const phasesData = [
  {
    id: 1,
    name: "Phase 1: Foundations of AI",
    description:
      "Get introduced to AI concepts, Python basics, and the mathematics that powers machine learning.",
    duration: "4 weeks",
    lessonsCount: 16,
    status: "completed",
    progress: 100,
    weeks: [
      {
        id: "1-1",
        number: 1,
        title: "Introduction to AI & Python",
        lessons: 4,
        duration: "3h 20m",
        status: "completed",
      },
      {
        id: "1-2",
        number: 2,
        title: "Data Handling with NumPy & Pandas",
        lessons: 4,
        duration: "4h 10m",
        status: "completed",
      },
      {
        id: "1-3",
        number: 3,
        title: "Linear Algebra & Statistics Refresher",
        lessons: 4,
        duration: "3h 45m",
        status: "completed",
      },
      {
        id: "1-4",
        number: 4,
        title: "Data Visualization & EDA",
        lessons: 4,
        duration: "3h 30m",
        status: "completed",
      },
    ],
    hasEvaluation: true,
    evaluationLink: "https://meet.google.com/abc-defg-hij",
  },
  {
    id: 2,
    name: "Phase 2: Supervised Machine Learning",
    description:
      "Master regression, classification, and the core algorithms that drive supervised learning.",
    duration: "4 weeks",
    lessonsCount: 16,
    status: "in-progress",
    progress: 50,
    weeks: [
      {
        id: "2-1",
        number: 1,
        title: "Linear & Logistic Regression",
        lessons: 4,
        duration: "4h 05m",
        status: "completed",
      },
      {
        id: "2-2",
        number: 2,
        title: "Decision Trees & Random Forests",
        lessons: 4,
        duration: "3h 55m",
        status: "in-progress",
      },
      {
        id: "2-3",
        number: 3,
        title: "Support Vector Machines",
        lessons: 4,
        duration: "4h 20m",
        status: "locked",
      },
      {
        id: "2-4",
        number: 4,
        title: "Model Evaluation & Tuning",
        lessons: 4,
        duration: "3h 40m",
        status: "locked",
      },
    ],
    hasEvaluation: true,
    evaluationLink: "https://meet.google.com/xyz-uvwx-yz1",
    quizLink: "/quizzes",
  },
  {
    id: 3,
    name: "Phase 3: Unsupervised Learning & Deep Learning",
    description:
      "Explore clustering, dimensionality reduction, and neural networks to round out your AI toolkit.",
    duration: "4 weeks",
    lessonsCount: 16,
    status: "locked",
    progress: 0,
    weeks: [
      {
        id: "3-1",
        number: 1,
        title: "K-Means & Hierarchical Clustering",
        lessons: 4,
        duration: "3h 50m",
        status: "locked",
      },
      {
        id: "3-2",
        number: 2,
        title: "PCA & Dimensionality Reduction",
        lessons: 4,
        duration: "3h 30m",
        status: "locked",
      },
      {
        id: "3-3",
        number: 3,
        title: "Intro to Neural Networks",
        lessons: 4,
        duration: "4h 15m",
        status: "locked",
      },
      {
        id: "3-4",
        number: 4,
        title: "Deep Learning with TensorFlow",
        lessons: 4,
        duration: "4h 45m",
        status: "locked",
      },
    ],
    hasEvaluation: true,
    evaluationLink: "https://meet.google.com/pqr-stuv-wx2",
    quizLink: "/quizzes",
  },
];

// Final capstone project shown at the very bottom of the page
export const capstoneProject = {
  title: "Capstone Project: AI in the Real World",
  description:
    "Build an end-to-end machine learning solution to solve a real-world problem, and present it to your cohort.",
  duration: "2 weeks",
  status: "locked",
  submissionLink: "/project",
};